# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gincontextleak < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haruyama480/gincontextleak/releases/download/v0.0.4/gincontextleak_Darwin_x86_64.tar.gz"
      sha256 "461810e75ba4c43c8c756e95edfe10fefa8a5708a053e5bde1744c7273877da4"

      define_method(:install) do
        bin.install "gincontextleak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haruyama480/gincontextleak/releases/download/v0.0.4/gincontextleak_Darwin_arm64.tar.gz"
      sha256 "edd5e5c61dce591f3ca47e06f8b45305a5b13a6c5d18fd51636e18fcdf15b9b5"

      define_method(:install) do
        bin.install "gincontextleak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/gincontextleak/releases/download/v0.0.4/gincontextleak_Linux_x86_64.tar.gz"
      sha256 "45866a6da68f8c692ba2374cdb5dee9378a1f749c84974464d080c574f98f4ab"
      define_method(:install) do
        bin.install "gincontextleak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/gincontextleak/releases/download/v0.0.4/gincontextleak_Linux_arm64.tar.gz"
      sha256 "b642f43bbb74f749178d49e92d9bd3d3f08f171d5496c5d111bf4549286d4b82"
      define_method(:install) do
        bin.install "gincontextleak"
      end
    end
  end
end
