# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallGodist < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.7/install-godist_Darwin_x86_64.tar.gz"
      sha256 "6fd1de6bd5fbee3576521e8d0e0dbef6f0bdee3798089fe0e0dc8748d5414011"

      define_method(:install) do
        bin.install "install-godist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.7/install-godist_Darwin_arm64.tar.gz"
      sha256 "4e39eeeb012c071a63547dd8fc25af5105bfb9fd8be89e588db9172250ad35c1"

      define_method(:install) do
        bin.install "install-godist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.7/install-godist_Linux_x86_64.tar.gz"
      sha256 "5b7aa16fa332e728b26cd42f873d1705d93b5d0ad3d2a3c5440cc00c14e8a9cd"
      define_method(:install) do
        bin.install "install-godist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.7/install-godist_Linux_arm64.tar.gz"
      sha256 "fb24f10b397053c4aaff8df1da453298eeae4bca50b9a0c181e9c5f5a7c7f97c"
      define_method(:install) do
        bin.install "install-godist"
      end
    end
  end
end
