# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallGodist < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.6/install-godist_Darwin_x86_64.tar.gz"
      sha256 "feae78563a95339823e119d66556f053edd0beaa0ac247266cad44117e3c3960"

      define_method(:install) do
        bin.install "install-godist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.6/install-godist_Darwin_arm64.tar.gz"
      sha256 "88525d7e28ecfb2aa16e7e55dc5cdcde2ec349d74fbe4c3af9b3a887d5fe5c0e"

      define_method(:install) do
        bin.install "install-godist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.6/install-godist_Linux_x86_64.tar.gz"
      sha256 "13878593b15796f83c09a3baab0be8f9d5c32130db1d56a8b2e1626558e28ac2"
      define_method(:install) do
        bin.install "install-godist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haruyama480/install-godist/releases/download/v0.0.6/install-godist_Linux_arm64.tar.gz"
      sha256 "fa16b8c5d7a30da98151395360950de0d9ded7ea57b9845225ab0ba4183ab0b7"
      define_method(:install) do
        bin.install "install-godist"
      end
    end
  end
end
