# This file was generated by GoReleaser. DO NOT EDIT.
cask "gincontextleak" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "08eb99629507ac8c63f2fdf7e70510b6c17a3bbecf832050534227952296799a"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "24741aa650050d78f9a52ddbb85e5dfff2ccf27c7f457cd62202ee95cc6a3326"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  on_linux do
    on_intel do
      sha256 "782e34f53142d2ec99e38de625dfc26bb53f162b7920fe57c0d7f71988746c94"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "bc0fabcf2bf4696a40b65638e8aa651878463c0cf6fd34a2aecaacaadafa4efa"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  name "gincontextleak"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gincontextleak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gincontextleak"]
    end
  end

  # No zap stanza required

end
