# This file was generated by GoReleaser. DO NOT EDIT.
cask "gincontextleak" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "43c71df5e39eb60b2bc21ea80b22a8b73d8b4de3a596e3acb25f0cc00a495d3b"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "ef61bdab0020a635fb0f7bc605055d588cf998e6c1fc974a86476f3b339cf4ea"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8012c915704bbaf141080d1983cde85aeccaa02e1baee8a3c99b4424f3661f3"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "cd85c5c8d37102dd35a9784c0605e9a97bf631906db71756b91200d3efee7185"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  name "gincontextleak"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gincontextleak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gincontextleak"]
    end
  end

  # No zap stanza required

end
