# This file was generated by GoReleaser. DO NOT EDIT.
cask "gincontextleak" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "e3b8b628375c4d45434e9887bd0019e2d7d08e69a1b91e662e22f141f17b8fd4"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "798cc18a06ed2f5f6cea8061c0d265405a72eb2acd724fa47d3c485871b82a11"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Darwin_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  on_linux do
    on_intel do
      sha256 "b19c2e34453faf3189b5b57b5b9e0a4113b77752bb9f6a1cc1b3cc9c27f8b918"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_x86_64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
    on_arm do
      sha256 "c2595e0d76d212f0339cc2be15cae8901038779df5d8dc0713b3853116f3a503"
      url "https://github.com/haruyama480/gincontextleak/releases/download/v#{version}/gincontextleak_Linux_arm64.tar.gz",
        verified: "github.com/haruyama480/gincontextleak"
    end
  end

  name "gincontextleak"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gincontextleak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gincontextleak"]
    end
  end

  # No zap stanza required

end
