# This file was generated by GoReleaser. DO NOT EDIT.
cask "install-godist" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "6fd1de6bd5fbee3576521e8d0e0dbef6f0bdee3798089fe0e0dc8748d5414011"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Darwin_x86_64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
    on_arm do
      sha256 "4e39eeeb012c071a63547dd8fc25af5105bfb9fd8be89e588db9172250ad35c1"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Darwin_arm64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b7aa16fa332e728b26cd42f873d1705d93b5d0ad3d2a3c5440cc00c14e8a9cd"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Linux_x86_64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
    on_arm do
      sha256 "fb24f10b397053c4aaff8df1da453298eeae4bca50b9a0c181e9c5f5a7c7f97c"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Linux_arm64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
  end

  name "install-godist"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "install-godist"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/install-godist"]
    end
  end

  # No zap stanza required

end
