# This file was generated by GoReleaser. DO NOT EDIT.
cask "install-godist" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "80ecb7b83387943a0140ddec8467f900a48be8ae5edadf8a4c038f1fe2153f4c"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Darwin_x86_64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
    on_arm do
      sha256 "527d1abaa515ce161917da023425bbb0927cbd1aa04606ccfd9cda57cee1e312"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Darwin_arm64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa6712bb3cf53b7ed951d73738ef78dbd8b9934fa596aad74864dc320ae00442"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Linux_x86_64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
    on_arm do
      sha256 "81c7c38a0446c8622c51fc92292b47873c233a60eac52a2894c499335e8e63d2"
      url "https://github.com/haruyama480/install-godist/releases/download/v#{version}/install-godist_Linux_arm64.tar.gz",
        verified: "github.com/haruyama480/install-godist"
    end
  end

  name "install-godist"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "install-godist"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/install-godist"]
    end
  end

  # No zap stanza required

end
